steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: [ "install", "-r", "src/requirements.txt", "--user" ]

  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/ndc-sftp-b2c-idl-import', '-f', './deployment/Dockerfile', '.']

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/ndc-sftp-b2c-idl-import']